### ISSUE TITLE
Bit_set cannot clone source

### ISSUE THREAD

**Issue by shizhuoer** [rhalbersma/bit_set#11]
Hi all,

The MSVC team recently test encountered a problem: Bit_set cannot clone source. Could you please help look at this issue? Thanks in advance.

**Repro steps:**
git clone https://github.com/rhalbersma/bit_set.git

**Error Info:**
Cloning into 'bit_set'...
remote: Enumerating objects: 2562, done.
remote: Counting objects: 100% (406/406), done.
remote: Compressing objects: 100% (213/213), done.
remote: Total 2562 (delta 223), reused 321 (delta 145), pack-reused 2156
Receiving objects: 100% (2562/2562), 470.72 KiB | 1.54 MiB/s, done.
Resolving deltas: 100% (1411/1411), done.
error: invalid path 'test/include/aux/bit_set.hpp'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by xiaoxiao-Xu** [comment]
@rhalbersma I'm so sorry. Could you please help take a quick look? Thanks in advance.

**Comment by rhalbersma** [comment]
@xiaoxiao-Xu and @shizhuoer sorry, I had GitHub email notification turned off by accident. Just tried this on my Linux dev box and I got no such error. So this seems irreproducible to me. Could you try again in a fresh directory?

**Comment by rhalbersma** [comment]
It appears that I can't use "aux" as a directory name since that will confuse Windows. Pff, OK, I will rename.

**Comment by rhalbersma** [comment]
@xiaoxiao-Xu @shizhuoer Could you please confirm that this issue is fixed on your end too?

**Comment by shizhuoer** [comment]
@rhalbersma I'm very sorry for not replying to you in time, because we were on vacation some time ago, I have verified that the problem has been solved, thank you very much for your help.
