### ISSUE TITLE
Why is there no operator[] overloading ?

### ISSUE THREAD

**Issue by wehostadm** [rhalbersma/bit_set#13]
Hi,

I would like to test your bitset implementation but there is no operator[] overloading.
Is it normal ?

And what is the performance of your implementation over std::bitset ?

Thanks,

**Comment by rhalbersma** [comment]
Hi, (I had comment forwarding turned off, so didn't notice this before). 

`bit_set<N>` is a packed representation for `std::set<int>`. Set have bidirectional iterators, no random access iterators and also no `operator[]`. 

I don't have systematic performance tests available. That might change in the future, but no promises.
