### ISSUE TITLE
insert(value_type const& x).second is always true

### ISSUE THREAD

**Issue by cnettel** [rhalbersma/bit_set#9]
A proper set<> will return true only if the element did not already exist. The current implementation always returns true.

The fix to check whether the bit is already set seems trivial, but I suppose that might incur some performance penalty unless the compiler will be able to conclude that the return value is not used (which is, arguably, the most frequent case).

**Comment by rhalbersma** [comment]
According to https://en.cppreference.com/w/cpp/container/set/insert:

> Returns a pair consisting of an iterator to the inserted element (or to the element that prevented the insertion) and a bool value set to true if the insertion took place.

`std::set<>` will first check if the element to be inserted is already present, and only then actually do the insert (which has a node allocation cost). In `xstd::bit_set<>`, we can do an unconditonal bitwise-OR when inserting without affecting the state of the container. And therefore returning an unconditional `true` as the second `pair` member is actually what is happening.

**Comment by rhalbersma** [comment]
Would it help if I added an `unconditional_insert` member that does what the current `insert` does? And then add presence-checking for `insert`?

**Comment by cnettel** [comment]
That would make sense to me, making the identically named one behaving in an identical way to a conventional set, but keeping ready access to a shortcut version doing a plain insert.

**Comment by rhalbersma** [comment]
Finally got around looking at this. You are right: the Standard mandates returning the presence prior to insertion. Also `erase()` requires the return of the presence prior to erasure. I will add Pythonesque named `add()` and `pop()` members that return `*this to allow chaining, and fix `insert` and `erase`.

**Comment by rhalbersma** [comment]
I fixed `insert` and `erase` to fully conform to the C++20 Standard and added the appropriate tests. Could you check if your use case is now working as desired? Note that you can use `add()` and `pop()` to insert and erase elements using member function chaining, equivalent to `std::bitset`'s `set` and `reset`.

**Comment by rhalbersma** [comment]
Should be fixed now, If not, I'll re-open.
